Repository YoelMantari/GitOps-Local, pull requests merged in 2025-06, with the labels that each got.

#3 Feature/terraform inicial mitchel
  CHANGELOG.md
  terraform/servicio_a/main.tf
  terraform/servicio_b/main.tf
Labels: documentation, enhancement

#17 Feature/deploy pipeline mitchel
  .git_hooks/commit-msg
  CHANGELOG.md
  README.md
  scripts/cola_dummy.py
  scripts/deploy_all.sh
  scripts/instala_servicio.sh
  scripts/validate.sh
  terraform/servicio_a/main.tf
  terraform/servicio_b/main.tf
  terraform/servicio_c/main.tf
  terraform/servicio_d/main.tf
Labels: enhancement, high priority, chore, Sprint 2

#18 Agregar un script de validación de servicios y generación de reporte JSON
  terraform/servicio_a/main.tf
  terraform/servicio_b/main.tf
  terraform/servicio_c/main.tf
  terraform/servicio_d/main.tf
  tools/generar_diagrama.py
  tools/verificar_estado.py
Labels: feature
